# Nome do Workflow
name: DevOpsLab Pipeline

# Evento que irá acionar a pipeline
on:
  push:
    branches:
      - main
      - GA-pipeline

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Download do Repositório
        uses: actions/checkout@v3       # https://github.com/actions/checkout

      - name: Setup Python
        uses: actions/setup-python@v4   # https://github.com/actions/setup-python
        with:
          python-version: '3.10'

      # Future steps to test the app
      # - name: Install Requirements
      #   run: pip install flask pytest pytest-cov flask-wtf flask-cors PyMySQL cryptography
      #
      # - name: Unit Test
      #   run: |
      #     coverage run --source=app -m pytest test.py
      #     coverage report -m
      #     coverage xml -i

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
